// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_cASkU1PdNdr9R2Lpv1M8_MzkTwQh_xw',
    appId: '1:650312010960:web:001c2eace1581db423a2d5',
    messagingSenderId: '650312010960',
    projectId: 'simulapp-92286',
    authDomain: 'simulapp-92286.firebaseapp.com',
    storageBucket: 'simulapp-92286.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhJ9wplQ5PMg8ptgKmZzqdAzXLYyhLbkw',
    appId: '1:650312010960:android:15cd5f6be831578d23a2d5',
    messagingSenderId: '650312010960',
    projectId: 'simulapp-92286',
    storageBucket: 'simulapp-92286.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuwfZxSatI_OE4b2ihHpc__O5CuacAIO8',
    appId: '1:650312010960:ios:8b7e87ce6e08c1e723a2d5',
    messagingSenderId: '650312010960',
    projectId: 'simulapp-92286',
    storageBucket: 'simulapp-92286.appspot.com',
    iosBundleId: 'com.example.simulapp',
  );
}
